import path from "node:path";
import { atomic } from "./files.ts";
import type { RunReport } from "./runner.ts";
const escape = (v: unknown) =>
  String(v).replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ]!,
  );
export function html(report: RunReport): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>AgentLedger · ${escape(report.name)}</title><style>
:root{font-family:system-ui,sans-serif;color:#e8ecf7;background:#0b111e;color-scheme:dark}body{max-width:1150px;margin:auto;padding:48px 24px}header{border-bottom:1px solid #334158;padding-bottom:30px}.eyebrow{color:#c4b5fd;letter-spacing:.18em;text-transform:uppercase;font-size:12px}h1{font-size:clamp(40px,7vw,74px);letter-spacing:-.05em;margin:10px 0}p{color:#adb9cc;line-height:1.65}.summary{display:flex;gap:18px;flex-wrap:wrap;margin:25px 0}.summary strong{background:#19263b;padding:18px;border-radius:10px}.task{border:1px solid #304159;border-radius:14px;margin:18px 0;padding:24px;background:#121e30}.badge{font:12px ui-monospace,monospace;letter-spacing:.1em;text-transform:uppercase;padding:5px 10px;background:#354158;border-radius:6px}.success,.cached,.passed{color:#94e9bd;background:#163f35}.failed,.timeout,.cancelled{color:#ffb3b9;background:#4c2533}pre{background:#0b1422;padding:16px;border-radius:8px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.65}h2{font-size:23px}h3{font-size:16px;color:#c4b5fd}table{border-collapse:collapse;width:100%;font-size:12px}td,th{border-bottom:1px solid #334158;padding:12px;text-align:left;overflow-wrap:anywhere}code{font-family:ui-monospace,monospace}.opinion{border-left:3px solid #d4b25c;padding:12px}.proof{border-left:3px solid #73dbab;padding:12px}footer{font-size:12px;margin-top:40px;color:#adb9cc}.hash{word-break:break-all}a{color:#c4b5fd}@media(max-width:600px){body{padding:25px 12px}.task{padding:16px}td,th{padding:6px}}@media print{:root{background:white;color:black}.task,pre,.summary strong{background:#f2f5f8;color:black}p,footer{color:#333}.task{break-inside:avoid}}
</style></head><body><header><div class="eyebrow">Local workflow report</div><h1>AgentLedger</h1><p>${escape(report.name)}</p><span class="badge ${escape(report.status)}">${escape(report.status)}</span></header><div class="summary"><strong>${report.tasks.length} tasks</strong><strong>${report.tasks.filter((t) => t.status === "cached").length} reused</strong><strong>${report.tasks.reduce((n, t) => n + t.artifacts.length, 0)} verified artifacts</strong></div><p>Command results, artifact hashes and model reviews are listed separately. Model reviews do not change command outcomes. Reports are unsigned; commands run with local OS permissions.</p>${report.tasks.map((t) => `<article class="task"><span class="badge ${escape(t.status)}">${escape(t.status)}</span><h2 id="task-${escape(t.id)}">${escape(t.id)}</h2><p>Dependencies: ${t.dependencies.length ? t.dependencies.map((id) => `<a href="#task-${escape(id)}">${escape(id)}</a>`).join(" · ") : "none"}</p><p>${t.attempts} attempt(s) · ${(t.durationMs / 1000).toFixed(3)} s · exit ${t.exitCode ?? "n/a"}${t.command ? ` (expected ${t.expectedExit})` : ""} · cwd ${escape(t.cwd)}</p>${t.command ? `<h3>Argument array · no implicit shell</h3><pre>${escape(JSON.stringify(t.command, null, 2))}</pre>` : ""}${t.reason ? `<p>${escape(t.reason)}</p>` : ""}${t.artifacts.length ? `<h3>Verified outputs</h3><table><tr><th>Path</th><th>Bytes</th><th>SHA-256</th></tr>${t.artifacts.map((a) => `<tr><td>${escape(a.path)}</td><td>${a.bytes}</td><td class="hash">${escape(a.sha256)}</td></tr>`).join("")}</table>` : ""}${t.automatedProof ? `<div class="proof"><h3>Automated review evidence</h3><p>Passed command checks: ${escape(t.automatedProof.checks.join(", "))}</p><pre>${escape(JSON.stringify(t.automatedProof.artifacts, null, 2))}</pre></div>` : ""}${t.modelOpinion ? `<div class="opinion"><h3>Model review</h3><p>${escape(t.modelOpinion.verdict)}</p><p>${escape(t.modelOpinion.rationale)}</p></div>` : ""}${t.output !== undefined ? `<details><summary>Explicitly included child output${t.outputTruncated ? " (truncated)" : ""}</summary><pre>${escape(t.output)}</pre></details>` : ""}<details><summary>Resume fingerprint</summary><pre>${escape(t.fingerprint)}</pre></details></article>`).join("")}<footer>Started ${escape(report.startedAt)} · Finished ${escape(report.finishedAt)} · ${escape(report.node)}<br>AgentLedger by nazeeh111 · MIT · Offline report.</footer></body></html>`;
}
export async function saveReport(report: RunReport, out: string) {
  await atomic(
    path.join(out, "report.json"),
    JSON.stringify(report, null, 2) + "\n",
  );
  await atomic(path.join(out, "index.html"), html(report));
}
